[package]
name = "check-downstream-compiles"
version = "0.1.0"
edition = "2021"

[dependencies]
camino = "1.1.7"
clap = { version = "4.5.13", features = ["derive"] }
env_logger = "0.11.5"
log = "0.4.22"
toml_edit = "0.22.20"
walkdir = "2.5.0"
