# Creates a PR benchmark comment with a comparison to main
# Restrictions
# - Only use with `issue_comment` trigger on a PR
# - Only runs with single benchmark due to `criterion` limitations (can be worked around, see criterion-compare-action below)
name: Benchmark pull requests

on:
  workflow_call:
    inputs:
      runner:
        required: false
        default: 'ubuntu-latest'
        type: string
      bench:
        required: true
        type: string

# TODO: Configure env vars via the `!benchmark` comment body instead of `bench.env`
jobs:
  cpu-benchmark:
    name: Run CPU benchmark
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: lurk-lab/ci-workflows
      - uses: ./.github/actions/gpu-setup
        with:
          gpu-framework: 'cuda'
      - uses: ./.github/actions/ci-env
      - uses: actions/checkout@v4
      - name: Checkout PR branch
        run: gh pr checkout $PR_NUMBER
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.issue.number }}
      # Install dependencies
      - name: Install dependencies
        run: sudo apt-get install -y pkg-config libssl-dev
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Set output type
        run: |
          echo "LURK_BENCH_OUTPUT=pr-comment" >> $GITHUB_ENV
      - uses: cardinalby/export-env-action@v2
        with:
          envFile:
            'benches/bench.env'
      # Run the comparative benchmark and comment output on the PR
      - uses: boa-dev/criterion-compare-action@v3
        with:
          # Note: Removing `benchName` causes `criterion` errors: https://github.com/boa-dev/criterion-compare-action#troubleshooting
          # Optional. Compare only this benchmark target
          benchName: "${{ inputs.bench }}"
          # Needed. The name of the branch to compare with
          branchName: ${{ github.ref_name }}

  gpu-benchmark:
    name: Run GPU benchmark
    runs-on: [self-hosted, "${{ inputs.runner }}"]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: lurk-lab/ci-workflows
      - uses: ./.github/actions/gpu-setup
        with:
          gpu-framework: 'cuda'
      - uses: ./.github/actions/ci-env
      - uses: actions/checkout@v4
      - name: Checkout PR branch
        run: gh pr checkout $PR_NUMBER
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.issue.number }}
      # Install dependencies
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Set output type
        run: echo "LURK_BENCH_OUTPUT=pr-comment" >> $GITHUB_ENV
      - uses: cardinalby/export-env-action@v2
        with:
          envFile: 'benches/bench.env'
      # Run the comparative benchmark and comment output on the PR
      - uses: boa-dev/criterion-compare-action@v3
        with:
          # Note: Removing `benchName` causes `criterion` errors: https://github.com/boa-dev/criterion-compare-action#troubleshooting
          # Optional. Compare only this benchmark target
          benchName: "${{ inputs.bench }}"
          # Optional. Features activated in the benchmark
          features: "cuda"
          # Needed. The name of the branch to compare with
          branchName: ${{ github.ref_name }}
