name: Check upstream `lurk-rs` compiles

on:
  workflow_call:
    inputs:
      runner:
        required: false
        default: 'ubuntu-latest'
        type: string
      # Name of the crate when imported by Lurk
      dependency-name:
          required: true
          type: string
      # Optional `Cargo.toml` `package` override
      package-name:
        required: false
        type: string

jobs:
  check-lurk-compiles:
    if: github.event_name == 'pull_request'
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: lurk-lab/ci-workflows
      - uses: ./.github/actions/ci-env
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: lurk-lab/lurk-rs
          path: ./lurk-rs
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Patch Cargo.toml
        working-directory: ${{ github.workspace }}/lurk-rs
        run: |
          # the dependency we want to patch is usually the same as the package, but
          # we e.g. want to override dependency 'nova' with an 'arecibo' package
          echo "[patch.'https://github.com/${{ github.repository }}']" >> Cargo.toml
          if [ ! -z "${{ inputs.package-name }}" ];
          then
            echo "${{ inputs.dependency-name }} = { path='../', package='${{ inputs.package-name }}' }" >> Cargo.toml
          else
            echo "${{ inputs.dependency-name }} = { path='../' }" >> Cargo.toml
          fi
      - name: Check Lurk-rs types don't break spectacularly
        working-directory: ${{ github.workspace }}/lurk-rs
        run: cargo check --workspace --tests --benches --examples
