name: CI Tests

on:
  push:
    branches: main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: CI Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: argumentcomputer/ci-workflows
      - uses: ./.github/actions/ci-env
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@nextest
      - name: Run tests
        run: cargo nextest run
        working-directory: ${{ github.workspace }}/crates/check-downstream-compiles

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: argumentcomputer/ci-workflows
      - uses: ./.github/actions/ci-env
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Check Rustfmt Code Style
        run: cargo fmt --all --check
        working-directory: ${{ github.workspace }}/crates/check-downstream-compiles
      - name: check *everything* compiles
        run: cargo check --all-targets --all-features --all --examples --tests --benches
        working-directory: ${{ github.workspace }}/crates/check-downstream-compiles
      # See '.cargo/config' for list of enabled/disabled clippy lints
      - name: Check clippy warnings
        run: cargo xclippy -D warnings
        working-directory: ${{ github.workspace }}/crates/check-downstream-compiles
