name: Generate and deploy Codecov results

on:
  workflow_call:
    inputs:
      runner:
        required: false
        default: 'ubuntu-latest'
        type: string

jobs:
  codecov-grcov:
    name: Generate code coverage
    runs-on: ${{ inputs.runner }}
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
        with:
          repository: lurk-lab/ci-workflows
      - uses: ./.github/actions/ci-env
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@nextest
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Clean the workspace
        run: cargo llvm-cov clean --workspace
      - name: Build
        run: cargo build --profile dev-ci
      - name: Collect coverage data
        run: cargo llvm-cov nextest --lcov --output-path lcov.info --profile ci --release --workspace
      - name: Upload coverage data to codecov
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
