name: Generate and deploy crate docs

on:
  workflow_call:

jobs:
  docs:
    name: Generate crate documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: lurk-lab/ci-workflows
      - uses: ./.github/actions/ci-env
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Generate documentation
        uses: actions-rs/cargo@v1
        env:
          RUSTDOCFLAGS: "--enable-index-page -Zunstable-options"
        with:
          command: doc
          args: --workspace --no-deps
      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
          destination_dir: docs
