# Uses deny.toml if found
name: cargo-deny

on:
  workflow_call:

jobs:
  cargo-deny:
    name: cargo-deny (advisories, licenses, bans, ...)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v1
