name: Check lints and code quality

on:
  workflow_call:
    inputs:
      # List of prerequisite Ubuntu packages, separated by whitespace
      packages:
        required: false
        type: string
      # Runs `cargo fmt +nightly`, for use with nightly config options in `rustfmt.toml` 
      nightly-fmt:
        required: false
        type: boolean

jobs:
  # Rustfmt, clippy, and doctests
  lints:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          repository: argumentcomputer/ci-workflows
      - uses: ./.github/actions/ci-env
      - uses: ./.github/actions/install-deps
        if: inputs.packages != ''
        with:
          packages: "${{ inputs.packages }}"
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: dtolnay/rust-toolchain@nightly
        if: inputs.nightly-fmt
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Check Rustfmt Code Style
        run: |
          if [[ "${{ inputs.nightly-fmt }}" == "true" ]]; then
            cargo +nightly fmt --all -- --check
          else
            cargo fmt --all -- --check
          fi
      - name: Check clippy warnings
        run: |
          if $(cargo --list|grep -q xclippy); then 
            cargo xclippy -Dwarnings
          else 
            cargo clippy -Dwarnings
          fi
      - name: Doctests
        run: cargo test --doc --workspace
