# NOTE: Does not currently work with Cargo workspaces
# See https://github.com/lurk-lab/ci-workflows/issues/8
name: Check MSRV

on:
  workflow_call:
    inputs:
      # List of prerequisite Ubuntu packages, separated by whitespace
      packages:
        required: false
        type: string

jobs:
  # Check MSRV (aka `rust-version`) in `Cargo.toml` is valid
  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: lurk-lab/ci-workflows
      - uses: ./.github/actions/ci-env
      - uses: ./.github/actions/install-deps
        if: inputs.packages != ''
        with:
          packages: "${{ inputs.packages }}"
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo-msrv
        run: cargo install cargo-msrv
      - name: Check Rust MSRV
        run: cargo msrv verify 
