# Checks whether Rust version specified in `rust-toolchain.toml` is out of date with latest stable
name: Rust Version Check


on:
  workflow_call:

jobs:
  rust-version-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Check out `ci-workflows`
        uses: actions/checkout@v4
        with:
          repository: lurk-lab/ci-workflows
          path: ci-workflows

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Get latest stable Rust version
        id: get-rust-version
        run: echo "RUST_VERSION=$(rustup check | grep stable | awk '{print $(NF-2)}')" >> $GITHUB_ENV

      - name: Parse rust-toolchain.toml
        id: parse-toolchain
        run: |
          CHANNEL=$(awk -F'\"' '/channel/ {print $2}' rust-toolchain.toml)
          if [[ $CHANNEL =~ ^[0-9]+\.[0-9]+(\.[0-9])?$ ]]; then
            echo "TOOLCHAIN_VERSION=$CHANNEL" >> $GITHUB_ENV
          else
            echo "TOOLCHAIN_VERSION=stable" >> $GITHUB_ENV
          fi

      - name: Compare Rust versions
        id: compare-versions
        run: |
          if [[ $TOOLCHAIN_VERSION != "stable" && $TOOLCHAIN_VERSION < $RUST_VERSION ]]; then
            echo "VERSION_MISMATCH=true" >> $GITHUB_ENV
          else
            echo "VERSION_MISMATCH=false" >> $GITHUB_ENV
          fi
      - uses: JasonEtco/create-an-issue@v2
        if: env.VERSION_MISMATCH == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
          update_existing: true
          filename: ci-workflows/.github/templates/VERSION_CHECK.md
